### ISSUE TITLE
评价

### ISSUE THREAD

**Issue by mengguanya** [Nekoqvq/Nekoqvq.github.io#1]
等级 A+
页面美观，知识点涉及全面，主题选择很贴近生活。主页不错！
为梦想点赞！

**Comment by Nekoqvq** [comment]
> 等级 A+
> 页面美观，知识点涉及全面，主题选择很贴近生活。主页不错！
> 为梦想点赞！

谢谢您的评价qvq！祝您代码不用debug，生活愉快！
